apiVersion: v1
kind: Service
metadata:
  name: cloud-native-go
  labels:
    app: cloud-native-go
    tier: service
spec:
# use NodePort here to be able to access a port on each node
  type: NodePort
  selector:
    app: cloud-native-go
  ports:
  - port: 8080
 
