apiVersion: v1
kind: Pod
metadata:
  name: cloud-native-go
  labels:
    language: cloud-native-go
    env: test
spec:
  containers:
  - name: cloud-native-go
    image: cloud-native-go:1.0.1-alpine
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
        protocol: TCP
